[package]
name = "saplinglib"
version = "0.1.0"
authors = ["Satinder Grewal"]
edition = "2018"

[lib]
name = "saplinglib"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"
saplingrustlib = { path = "lib" }